"""WAF (Web Application Firewall) detection tool."""
import urllib.request
import urllib.parse
import ssl
import re

TOOL_SCHEMA = {
    "name": "waf_detect",
    "description": (
        "Detect if a Web Application Firewall (WAF) is protecting the target. "
        "Identifies specific WAF products (Cloudflare, AWS WAF, ModSecurity, etc.). "
        "If WAF is present, the agent should adapt payloads to bypass it."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "url": {"type": "string", "description": "Target URL e.g. http://example.com"},
        },
        "required": ["url"],
    },
}

# Test payloads that should trigger a WAF
TRIGGER_PAYLOADS = [
    # SQL Injection
    "' OR 1=1--",
    "1 UNION SELECT NULL,NULL--",
    # XSS
    "<script>alert(1)</script>",
    '"><img src=x onerror=alert(1)>',
    # Path traversal
    "../../etc/passwd",
    # Command injection
    "; cat /etc/passwd",
    "| ls -la",
]

# WAF identification signatures
WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": {"server": "cloudflare", "cf-ray": ""},
        "body": ["attention required", "cloudflare ray id", "cf-browser-verification"],
        "codes": [403, 503],
    },
    "AWS WAF": {
        "headers": {"x-amzn-requestid": "", "x-amz-cf-id": ""},
        "body": ["aws waf", "request blocked"],
        "codes": [403],
    },
    "ModSecurity": {
        "headers": {"server": "mod_security"},
        "body": ["mod_security", "modsecurity", "not acceptable", "rule id"],
        "codes": [403, 406],
    },
    "Imperva / Incapsula": {
        "headers": {"x-cdn": "incapsula", "x-iinfo": ""},
        "body": ["incapsula incident", "_incapsula_resource", "imperva"],
        "codes": [403],
    },
    "Akamai": {
        "headers": {"x-akamai-transformed": "", "server": "akamaighost"},
        "body": ["akamai", "access denied", "reference #"],
        "codes": [403],
    },
    "Sucuri": {
        "headers": {"server": "sucuri", "x-sucuri-id": ""},
        "body": ["sucuri website firewall", "access denied - sucuri"],
        "codes": [403],
    },
    "F5 BIG-IP ASM": {
        "headers": {"server": "bigip", "x-cnection": ""},
        "body": ["the requested url was rejected", "support id"],
        "codes": [403],
    },
    "Barracuda": {
        "headers": {"server": "barracuda"},
        "body": ["barracuda", "barra_counter_session"],
        "codes": [403],
    },
    "Fortinet FortiWeb": {
        "headers": {"server": "fortiweb"},
        "body": ["fortigate", "fortinet", ".fgd_icon"],
        "codes": [403],
    },
    "DenyAll": {
        "headers": {"server": "denyall"},
        "body": ["conditionblocked", "denyall"],
        "codes": [403],
    },
    "Wordfence (WordPress)": {
        "headers": {},
        "body": ["wordfence", "generated by wordfence", "blocked by wordfence"],
        "codes": [403, 503],
    },
    "Comodo WAF": {
        "headers": {"server": "comodo"},
        "body": ["protected by comodo"],
        "codes": [403],
    },
    "nginx WAF / naxsi": {
        "headers": {},
        "body": ["request denied", "naxsi"],
        "codes": [403],
    },
}


def is_available() -> bool:
    return True


def _send_request(url: str, timeout: int = 10) -> dict | None:
    """Send request and return headers, body, status."""
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    try:
        req = urllib.request.Request(url)
        req.add_header("User-Agent", "GuardX-WAFDetect/0.1")
        with urllib.request.urlopen(req, timeout=timeout, context=ctx) as resp:
            headers = {k.lower(): v.lower() for k, v in resp.headers.items()}
            body = resp.read(100_000).decode("utf-8", errors="replace").lower()
            return {"headers": headers, "body": body, "status": resp.status}
    except urllib.error.HTTPError as e:
        try:
            body = e.read(100_000).decode("utf-8", errors="replace").lower()
        except Exception:
            body = ""
        headers = {k.lower(): v.lower() for k, v in e.headers.items()} if e.headers else {}
        return {"headers": headers, "body": body, "status": e.code}
    except Exception:
        return None


def _identify_waf(headers: dict, body: str, status: int) -> list[tuple[str, str]]:
    """Identify WAF from response. Returns list of (waf_name, evidence)."""
    detected = []

    for waf_name, sigs in WAF_SIGNATURES.items():
        evidence = []

        # Check headers
        for header, expected_val in sigs.get("headers", {}).items():
            actual = headers.get(header, "")
            if actual and (not expected_val or expected_val in actual):
                evidence.append(f"Header {header}={actual}")

        # Check body patterns
        for pattern in sigs.get("body", []):
            if pattern in body:
                evidence.append(f"Body contains '{pattern}'")
                break

        if evidence:
            detected.append((waf_name, "; ".join(evidence)))

    return detected


async def execute(params: dict) -> str:
    url = params["url"]
    if not url.startswith(("http://", "https://")):
        url = f"http://{url}"

    lines = [f"=== WAF Detection for {url} ===", ""]

    # Phase 1: Check normal response for WAF headers
    normal = _send_request(url)
    if normal is None:
        return f"Could not connect to {url}"

    lines.append(f"Normal request: HTTP {normal['status']}")

    # Check for WAF indicators in normal response
    normal_wafs = _identify_waf(normal["headers"], normal["body"], normal["status"])

    # Phase 2: Send malicious payloads to trigger WAF
    lines.append("\n--- Sending trigger payloads ---")
    triggered_wafs = []
    blocked_count = 0
    total_payloads = len(TRIGGER_PAYLOADS)

    for payload in TRIGGER_PAYLOADS:
        # Try as URL parameter
        test_url = f"{url.rstrip('/')}/?guardx_test={urllib.parse.quote(payload)}"
        result = _send_request(test_url)

        if result is None:
            lines.append(f"  Payload: {payload[:30]}... -> Connection dropped (possible WAF)")
            blocked_count += 1
            continue

        if result["status"] in (403, 406, 429, 503):
            blocked_count += 1
            lines.append(f"  Payload: {payload[:30]}... -> BLOCKED (HTTP {result['status']})")

            # Try to identify which WAF blocked it
            wafs = _identify_waf(result["headers"], result["body"], result["status"])
            triggered_wafs.extend(wafs)
        else:
            lines.append(f"  Payload: {payload[:30]}... -> Passed (HTTP {result['status']})")

    # Combine all detected WAFs
    all_wafs = {}
    for waf_name, evidence in normal_wafs + triggered_wafs:
        if waf_name not in all_wafs:
            all_wafs[waf_name] = set()
        all_wafs[waf_name].add(evidence)

    # Build verdict
    lines.append("")
    lines.append("=" * 50)

    if all_wafs:
        lines.append(f"\n[!] WAF DETECTED - {len(all_wafs)} product(s) identified:")
        for waf_name, evidences in all_wafs.items():
            lines.append(f"\n  >> {waf_name}")
            for ev in evidences:
                lines.append(f"     Evidence: {ev}")

        lines.append(f"\nBlocked payloads: {blocked_count}/{total_payloads}")
        lines.append("\n--- Recommendations for the agent ---")
        lines.append("  - Use WAF bypass payloads from skills knowledge base")
        lines.append("  - Try encoding: URL-encode, double-encode, unicode")
        lines.append("  - Try case alternation: SeLeCt, UnIoN")
        lines.append("  - Try comment injection: /**/UNION/**/SELECT")
        lines.append("  - Try HTTP parameter pollution")
        lines.append("  - Try different HTTP methods (POST vs GET)")
        lines.append("  - Try payloads in different positions (headers, cookies)")

    elif blocked_count > total_payloads * 0.5:
        lines.append(f"\n[!] PROBABLE WAF (unidentified)")
        lines.append(f"Blocked payloads: {blocked_count}/{total_payloads}")
        lines.append("WAF product could not be identified but blocking behavior detected.")
        lines.append("Use evasion techniques when testing vulnerabilities.")

    else:
        lines.append(f"\n[OK] No WAF detected")
        lines.append(f"Blocked payloads: {blocked_count}/{total_payloads}")
        lines.append("Standard payloads should work without evasion techniques.")

    return "\n".join(lines)
